import{a as M,S as E,i as n}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const h=async(t,o=1,r=15)=>{const a=await M.get("https://pixabay.com/api/",{params:{key:"48303854-cd498063b7025b62fb7eab433",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:r}});if(a.status!==200)throw new Error(`Error: ${a.status}`);return a.data};let u;const m=t=>{const o=document.querySelector(".gallery"),r=t.map(({webformatURL:a,largeImageURL:e,tags:s,likes:l,views:S,comments:q,downloads:v})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${a}" alt="${s}" />
        </a>
        <div class="info">
          <p><span>Likes</span> ${l}</p>
          <p><span>Views</span> ${S}</p>
          <p><span>Comments</span> ${q}</p>
          <p><span>Downloads</span> ${v}</p>
        </div>
      </div>
    `).join("");o.insertAdjacentHTML("beforeend",r),u?u.refresh():u=new E(".gallery a",{captionsData:"alt",captionDelay:250})},I=()=>{document.querySelector(".gallery").innerHTML=""},g=()=>{document.querySelector(".load-more").style.display="block"},y=()=>{document.querySelector(".load-more").style.display="none"},f=document.querySelector(".js-search-form"),d=document.querySelector(".load-more"),L=document.querySelector("#initial-loader"),w=document.querySelector("#load-more-loader");let i=1,c="",p=!1;const P=()=>{L.style.display="block",d.style.display="none"},$=()=>{L.style.display="none"},R=()=>{w.style.display="block",d.style.display="none"},b=()=>{w.style.display="none"},O=async t=>{t.preventDefault();const o=t.target.elements.user_query;if(c=o?o.value.trim():"",!c){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}i=1,I(),y(),b();try{P();const r=await h(c,i);if(r.hits.length===0){n.info({title:"Info",message:"No images found. Try a different query!",position:"topRight"});return}m(r.hits),g(),i*15>=r.totalHits&&(y(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error("Error fetching images:",r),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{$(),t.target.reset()}},B=async()=>{if(!p){p=!0,i+=1,R();try{const t=await h(c,i);m(t.hits);const o=document.querySelectorAll(".photo-card");if(o.length>0){const r=o[0].getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}i*15>=t.totalHits?(y(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):g()}catch(t){console.error("Error loading more images:",t),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p=!1,b()}}};f&&f.addEventListener("submit",O);d&&d.addEventListener("click",B);
//# sourceMappingURL=index.js.map
