import{a as M,S as E,i as n}from"./assets/vendor-tnUJPedx.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const m=async(t,s=1,o=15)=>{const a=await M.get("https://pixabay.com/api/",{params:{key:"48303854-cd498063b7025b62fb7eab433",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:o}});if(a.status!==200)throw new Error(`Error: ${a.status}`);return a.data};let u;const h=t=>{const s=document.querySelector(".gallery"),o=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:l,views:S,comments:q,downloads:v})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${a}" alt="${r}" />
        </a>
        <div class="info">
          <p><span>Likes</span> ${l}</p>
          <p><span>Views</span> ${S}</p>
          <p><span>Comments</span> ${q}</p>
          <p><span>Downloads</span> ${v}</p>
        </div>
      </div>
    `).join("");s.insertAdjacentHTML("beforeend",o),u?u.refresh():u=new E(".gallery a",{captionsData:"alt",captionDelay:250})},P=()=>{document.querySelector(".gallery").innerHTML=""},g=()=>{document.querySelector(".load-more").style.display="block"},y=()=>{document.querySelector(".load-more").style.display="none"},f=document.querySelector(".js-search-form"),d=document.querySelector(".load-more"),L=document.querySelector("#initial-loader"),b=document.querySelector("#load-more-loader");let i=1,c="",p=!1;const $=()=>{L.style.display="block",d.style.display="none"},I=()=>{L.style.display="none"},O=()=>{b.style.display="block",d.style.display="none"},w=()=>{b.style.display="none"},R=async t=>{t.preventDefault();const s=t.target.elements.user_query;if(c=s?s.value.trim():"",!c){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}i=1,P(),y(),w();try{$();const o=await m(c,i);if(o.hits.length===0){n.info({title:"Info",message:"No images found. Try a different query!",position:"topRight"});return}h(o.hits),g(),i*15>=o.totalHits&&(y(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.error("Error fetching images:",o),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{I(),t.target.reset()}},x=async()=>{if(!p){p=!0,i+=1,O();try{const t=await m(c,i);h(t.hits),i*15>=t.totalHits?(y(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):g()}catch(t){console.error("Error loading more images:",t),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p=!1,w()}}};f&&f.addEventListener("submit",R);d&&d.addEventListener("click",x);
//# sourceMappingURL=index.js.map
