import{a as w,S as L}from"./assets/vendor-DBMDmZZa.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const f=async(t,o=1,a=15)=>{const s=await w.get("https://pixabay.com/api/",{params:{key:"48303854-cd498063b7025b62fb7eab433",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:a}});if(s.status!==200)throw new Error(`Error: ${s.status}`);return s.data};let d;const h=t=>{const o=document.querySelector(".gallery"),a=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:l,views:m,comments:g,downloads:b})=>`
      <div class="photo-card">
        <a href="${e}">
          <img src="${s}" alt="${r}" />
        </a>
        <div class="info">
          <p><span>Likes</span> ${l}</p>
          <p><span>Views</span> ${m}</p>
          <p><span>Comments</span> ${g}</p>
          <p><span>Downloads</span> ${b}</p>
        </div>
      </div>
    `).join("");o.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new L(".gallery a",{captionsData:"alt",captionDelay:250})},S=()=>{document.querySelector(".gallery").innerHTML=""},q=()=>{document.querySelector(".load-more").style.display="block"},u=()=>{document.querySelector(".load-more").style.display="none"},y=document.querySelector(".js-search-form"),p=document.querySelector(".load-more"),c=document.querySelector(".loader");let n=1,i="";const v=async t=>{t.preventDefault();const o=t.target.elements.user_query;if(i=o?o.value.trim():"",!i){alert("Please enter a search query!");return}n=1,S(),u();try{c.style.display="block";const a=await f(i,n);if(a.hits.length===0){alert("No images found. Try a different query!");return}h(a.hits),q(),n*15>=a.totalHits&&(u(),alert("We're sorry, but you've reached the end of search results."))}catch(a){console.error("Error fetching images:",a),alert("Something went wrong. Please try again later.")}finally{c.style.display="none",t.target.reset()}},P=async()=>{n+=1;try{c.style.display="block";const t=await f(i,n);h(t.hits),n*15>=t.totalHits&&(u(),alert("We're sorry, but you've reached the end of search results."));const{height:o}=document.querySelector(".gallery .photo-card").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}catch(t){console.error("Error loading more images:",t),alert("Something went wrong. Please try again later.")}finally{c.style.display="none"}};y&&y.addEventListener("submit",v);p&&p.addEventListener("click",P);
//# sourceMappingURL=index.js.map
